### ISSUE TITLE
Doesn't work anymore!

### ISSUE THREAD

**Issue by abhigenie92** [oh-my-fish/plugin-sudope#2] opened 2017-03-11 02:32 UTC
```
$ nano sources.listNo command 'string' found, did you mean:
 Command 'strings' from package 'binutils' (main)
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'spring' from package 'spring' (universe)
string: command not found
in command substitution
        called on line 1 of file ~/.local/share/omf/pkg/sudope/functions/sudope.fish

in function “sudope”
        called on standard input
```

**Comment by oranja** [comment] 2017-03-11 15:14
It doesn't work anymore with `fish 2.2`.
Fish is already at version 2.5 and the plugin could benefit from an upgrade, so we made the decision to drop support for version 2.2.

You are free to create a fork of this repository and roll it back to commit 1eb55d9, then install sudope from your own fork instead of this one.
If you need further assistance let me know.
I'm sorry for this inconvenience.

**Comment by abhigenie92** [comment] 2017-03-17 06:55
Using the latest version from the git repo.
```
 ✘  ⚙  ~  fish --version
fish, version 2.5.0-238-ga811ae2
 ⚙  ~  nano installNo command 'string' found, did you mean:
 Command 'spring' from package 'spring' (universe)
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'strings' from package 'binutils' (main)
 Command 'strings' from package 'binutils-multiarch' (main)
string: command not found
in command substitution
        called on line 1 of file ~/.local/share/omf/pkg/sudope/functions/sudope.fish

in function “sudope”
        called on standard input



```

**Comment by oranja** [comment] 2017-03-19 08:27
I'd rather have you check on a stable release of `fish`, but I doubt that the `string` builtin was removed by accident.

Does `echo $FISH_VERSION` say `2.5.0` as well?
I just tested on my Ubuntu test machine with fish 2.5.0 and a fresh copy of omf + sudope, and could not reproduce this error.

Any other clues you can give? Does this still happen to you?

**Comment by abhigenie92** [comment] 2017-03-20 10:33
```
 ~  echo $FISH_VERSION 
2.2.0
 ~  fish --version
fish, version 2.5.0-238-ga811ae2
```
Oh, you are right. But I am unsure what's happening. Can you expound on the issue here if possible.

**Comment by oranja** [comment] 2017-03-20 10:43
I can not say for certain, but the most likely theory I can come up with is that you only recently upgraded `fish` from 2.2.0 to 2.5.0, and still run the previous version of `fish` in your terminal.
To substitute the later version for the older version, you may run `exec fish`. Then verify that `echo $FISH_VERSION` mentions 2.5.0 and that everything works as expected.

**Comment by oranja** [comment] 2018-03-09 13:05
Hi @abhigenie92,
Any discoveries so far? Did you manage to solve it or you gave up?

**Comment by oranja** [comment] 2019-01-21 21:11
Closing due to lack of updates.

**Closed as completed by oranja** 2019-01-21 21:11 UTC
